
=============================== entering sandbox ===============================
task   : Train__home_muhammed_s_False_0_9e25f2035d
sandbox: deepclean::/home/muhammed.saleem/images/deepclean/train.sif
================================================================================


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/deepclean/projects/train/train/__main__.py", line 1, in <module>
    from train.cli import main
  File "/opt/deepclean/projects/train/train/cli.py", line 3, in <module>
    import torch
  File "/usr/local/lib/python3.10/site-packages/torch/__init__.py", line 1382, in <module>
    from .functional import *  # noqa: F403
  File "/usr/local/lib/python3.10/site-packages/torch/functional.py", line 7, in <module>
    import torch.nn.functional as F
  File "/usr/local/lib/python3.10/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/__init__.py", line 35, in <module>
    from .transformer import TransformerEncoder, TransformerDecoder, \
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/transformer.py", line 20, in <module>
    device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
/usr/local/lib/python3.10/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
Seed set to 101588
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
The following callbacks returned in `LightningModule.configure_callbacks` will override existing callbacks passed to Trainer: ModelCheckpoint
You are using a CUDA device ('NVIDIA A30') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
/usr/local/lib/python3.10/site-packages/lightning/fabric/loggers/csv_logs.py:269: Experiment logs directory /home/muhammed.saleem/deepClean/deepcleanv2/myprojects/60Hz-O3-MDC/results/lightning_logs/version_1 exists and is not empty. Previous log files in this directory will be deleted when the new ones are saved!
2024-07-07 15:52:30,900 - DeepClean Dataset - INFO - Inferred data sample rate 4096.0Hz
2024-07-07 15:52:30,900 - DeepClean Dataset - INFO - Setting up data for fit stage
2024-07-07 15:52:30,900 - DeepClean Dataset - INFO - Loading train data
2024-07-07 15:52:42,140 - DeepClean Dataset - INFO - Training on first 768.0 seconds, validating on remaining 256.0 seconds
2024-07-07 15:52:42,143 - DeepClean Dataset - INFO - Preprocessing training data
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/deepclean/projects/train/train/__main__.py", line 4, in <module>
    main()
  File "/opt/deepclean/projects/train/train/cli.py", line 90, in main
    cli.trainer.fit(cli.model, cli.datamodule)
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 543, in fit
    call._call_and_handle_interrupt(
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 579, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 948, in _run
    call._call_setup_hook(self)  # allow user to set up LightningModule in accelerator environment
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 94, in _call_setup_hook
    _call_lightning_datamodule_hook(trainer, "setup", stage=fn)
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 181, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
  File "/opt/deepclean/projects/train/train/data.py", line 195, in setup
    train_y = self.bandpass(train_y.numpy())
RuntimeError: Numpy is not available

=============================== leaving sandbox ================================
task   : Train__home_muhammed_s_False_0_9e25f2035d
sandbox: deepclean::/home/muhammed.saleem/images/deepclean/train.sif
================================================================================

/home/muhammed.saleem/deepClean/deepcleanv2/myprojects/60Hz-O3-MDC
